---
vector_config:
  data_dir: "/var/lib/vector"
  sources:
    our_log:
      type: file
      include:
        - "/home/cloud-user/logs/*.log"
      ignore_older: 600
      read_from: beginning
  sinks:
    to_clickhouse:
      inputs:
        - our_log
      type: clickhouse
      database: custom
      table: my_table
      endpoints: "http://51.250.90.79:8123"
      healthcheck: false
      compression: gzip
      skip_unknown_fields: true
