{
 "title": "MyLaptop",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[30m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load Average 1/5/15m",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_load1{instance=\"node-exporter:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load5{instance=\"node-exporter:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load15{instance=\"node-exporter:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Free",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"node-exporter:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem Free",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"node-exporter:9100\", mountpoint=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}